# =========================================
# APP
# =========================================
spring.application.name=finances

# =========================================
# GEMINI / GOOGLE GENAI
# =========================================

# API KEY
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# MODELO
# opções:
# gemini-1.5-flash
# gemini-1.5-pro
# gemini-2.0-flash
spring.ai.google.genai.chat.model=${GOOGLE_GENAI_MODEL:gemini-2.5-flash}

# TEMPERATURA
# menor = respostas mais precisas
# maior = mais criatividade
spring.ai.google.genai.chat.temperature=0.7

# TOKENS MÁXIMOS
spring.ai.google.genai.chat.max-output-tokens=2048

# TOP P
spring.ai.google.genai.chat.top-p=0.95

# TOP K
spring.ai.google.genai.chat.top-k=40
    
# =========================================
# LOGS
# =========================================

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web.client=DEBUG

# =========================================
# MULTIPART (áudio/imagem)
# =========================================

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# =========================================
# TIMEOUTS
# =========================================

spring.mvc.async.request-timeout=300000